export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ProductsLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-gray-50 min-h-full">
      {children}
    </div>
  );
}
